image: docker:git

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - apk --update --no-cache add bash
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
  - bash build.sh
