image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  NAMESPACE: edbizarro/gitlab-ci-pipeline-php

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

debian:7.1:
  stage: build
  variables:
    IMAGE_VERSION: "7.1"
  script:
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.1/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html edbizarro/gitlab-ci-pipeline-php:$IMAGE_VERSION goss v
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:latest
    - docker tag $NAMESPACE:$IMAGE_VERSION $NAMESPACE:7
    - docker push $NAMESPACE:7
    - docker push $NAMESPACE:$IMAGE_VERSION
    - docker push $NAMESPACE:latest

debian:7.0:
  stage: build
  variables:
    IMAGE_VERSION: "7.0"
  script:
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.0/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION

debian:5.6:
  stage: build
  script:
    - docker build --compress --cache-from $NAMESPACE:5.6 -t $NAMESPACE:5.6 -f php/5.6/Dockerfile .
    # - 'if docker run -t --rm edbizarro/gitlab-ci-pipeline-php:5.6 php -v | grep "PHP 5.6"; then return 0; else return 1; fi'
    - docker push $NAMESPACE:5.6

alpine:7.1:
  stage: build
  variables:
    IMAGE_VERSION: "7.1-alpine"
  script:
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.1/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION

alpine:7.0:
  stage: build
  variables:
    IMAGE_VERSION: "7.0-alpine"
  script:
    - docker build --compress --cache-from $NAMESPACE:$IMAGE_VERSION -t $NAMESPACE:$IMAGE_VERSION -f php/7.0/alpine/Dockerfile .
    - docker run -t --rm -v $(pwd):/var/www/html $NAMESPACE:$IMAGE_VERSION goss v
    - docker push $NAMESPACE:$IMAGE_VERSION

# fpm:5.6:
#   stage: build
#   script:
#     - docker build --compress --cache-from $NAMESPACE:5.6-fpm -t $NAMESPACE:5.6-fpm -f php/5.6/fpm/Dockerfile .
#     - docker push $NAMESPACE:5.6-fpm
#
# fpm:7.0:
#   stage: build
#   script:
#     - docker build --compress --cache-from $NAMESPACE:7.0-fpm -t $NAMESPACE:7.0-fpm -f php/7.0/fpm/Dockerfile .
#     - docker push $NAMESPACE:7.0-fpm
#
# fpm:7.1:
#   stage: build
#   script:
#     - docker build --compress --cache-from $NAMESPACE:7.1-fpm -t $NAMESPACE:7.1-fpm -f php/7.1/fpm/Dockerfile .
#     - docker tag $NAMESPACE:7.1-fpm $NAMESPACE:fpm
#     - docker push $NAMESPACE:7.1-fpm
#     - docker push $NAMESPACE:fpm
